# Generated by Django 4.1.3 on 2022-11-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                ("sex", models.CharField(default="Not informed", max_length=20)),
                ("traits", models.ManyToManyField(to="traits.trait")),
            ],
        ),
    ]
