# Generated by Django 4.1.3 on 2022-11-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='group',
        ),
    ]
