# Generated by Django 4.1.3 on 2022-11-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_pet'),
        ('traits', '0005_trait_created_at'),
        ('pets', '0004_remove_pet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='groups.group'),
        ),
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='pets', to='traits.trait'),
        ),
    ]
