# Generated by Django 4.1.3 on 2022-11-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0006_remove_trait_pet'),
        ('pets', '0005_pet_group_pet_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='traits',
        ),
        migrations.AddField(
            model_name='pet',
            name='trait',
            field=models.ManyToManyField(related_name='traits', to='traits.trait'),
        ),
    ]
