# Generated by Django 4.1.3 on 2022-11-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_remove_pet_traits_pet_trait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='trait',
        ),
    ]
