# Generated by Django 4.1.3 on 2022-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0008_remove_trait_pets"),
        ("pets", "0007_remove_pet_trait"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="trait",
            field=models.ManyToManyField(related_name="traits", to="traits.trait"),
        ),
    ]
