# Generated by Django 4.1.3 on 2022-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0008_remove_trait_pets"),
        ("pets", "0008_pet_trait"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="trait",
        ),
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
