# Generated by Django 4.1.3 on 2022-11-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='pet',
        ),
    ]
