# Generated by Django 4.1.3 on 2022-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_group'),
        ('traits', '0003_remove_trait_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='pet',
            field=models.ManyToManyField(to='pets.pet'),
        ),
    ]
