# Generated by Django 4.1.3 on 2022-11-29 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0004_trait_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 29, 13, 22, 55, 880563, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
