# Generated by Django 4.1.3 on 2022-11-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_trait_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='pet',
        ),
    ]
