# Generated by Django 4.1.3 on 2022-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_pet_trait'),
        ('traits', '0006_remove_trait_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='pets',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
