# Generated by Django 4.1.3 on 2022-11-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0007_trait_pets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pets",
        ),
    ]
