# Generated by Django 4.1.3 on 2022-11-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_remove_pet_traits"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pet",
        ),
        migrations.AddField(
            model_name="group",
            name="pet",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pets.pet"
            ),
        ),
    ]
