# Generated by Django 4.1.3 on 2022-11-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_group'),
        ('groups', '0003_remove_group_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
    ]
