# Generated by Django 4.1.3 on 2022-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_remove_group_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="scientific_name",
            field=models.CharField(max_length=50),
        ),
    ]
