# Generated by Django 4.1.3 on 2022-12-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0007_alter_group_scientific_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="scientific_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
